# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93d7607ae82aa002f03538077418e974707c56e84d32b2dad26a6f9a7772b0e66d4abd7ee1f1bd3b20f9b3ab059482ce76964eafddaaadd469aa5c7c791ac112

test:
  secret_key_base: 2afd5031c60e72954e80e1b43fceb9d4f4935fb50778c7499e46eb6faab02ee9652bec798118a565c0530603d14c310d6311d9345c41b64a843c1d97091e3448

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
